### ISSUE TITLE
RTC device /dev/rtc0 no longer in the build

### ISSUE THREAD

**Issue by pwittich** [apollo-lhc/SM_ZYNQ_FW#68]
No DTC device in the build. 

on boot:
```
[    3.278457] hctosys: unable to open rtc device (rtc0)
```
Confirmed in the shell
```
[root@localhost log]# ls -l /dev/rtc*
ls: cannot access /dev/rtc*: No such file or directory
```
I think this used to be there.

**Comment by dgastler** [comment]
This has been fixed with changes in the kernel build dir for the additional device tree files.
