### ISSUE TITLE
Change blade serial number in status display to decimal from hex

### ISSUE THREAD

**Issue by dgastler** [apollo-lhc/SM_ZYNQ_FW#78]
IPMC| ADDR|   ID|            IP|
               --|-----|-----|--------------|
              ETH|     |     | 192.168.22.34|
               RN|     |    1|              |
             SLOT| 0x88|     |              |
               SN|     | 0xCC|              |

**Comment by alpakpinar** [comment]
@dgastler, a possible solution to this is at #79. The newly built firmware + kernel seems to be working on SM209:

```
>status 1 IPMC
Process done
             IPMC| ADDR|  ID|            IP|
               --|-----|----|--------------|
              ETH|     |    | 192.168.22.37|
               RN|     |   1|              |
             SLOT| 0x8E|    |              |
               SN|     | 209|              |
```
